# Generated by Django 4.0.1 on 2022-02-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliderpic', models.ImageField(default='default.jpg', upload_to='images/')),
            ],
        ),
    ]
