# Generated by Django 4.0.1 on 2022-02-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
